world_all: Pillars
game:
  test:
    death_arena:
      - -100 -42 -100
      - 100 -30 100
    spawn_location:
      - 50.5 91 66.5
      - 50.5 92 35.5
      - 66.5 91 50.5
      - 34.5 91 50.5
      - 40.5 91 60.5
      - 60.5 91 40.5
      - 60.5 91 60.5
      - 40.5 91 40.5
    waiting_location:
      - 50.5 120 50.5
    worldborder:
      center: 50 50
      diameter: 100
      time: 300
      to: 2
    settings:
      schematic:
        cords: 0 80 0
        name: arena1
      chunk-delete:
        1pos: "-4 -4"
        2pos: "4 4"
      back-command: "world spawn"
      event_chance: 10
      time: 3000
      wait-min: 20
      wait-max: 3
      min-players: 2
      max-players: 8
      reward_interval: 3

    # Разные ивенты
    events:
      speed_boost:
        chance: 20
        commands:
          - "effect give @a speed 30 1"
      jump_boost:
        chance: 15
        commands:
          - "effect give @a jump_boost 30 1"

    # Предметы для выдачи
    items:
      type: blacklist # тип whitelist/blacklist
      diamond:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND
        amount: 3
      golden_apple:
        ==: org.bukkit.inventory.ItemStack
        type: GOLDEN_APPLE