name: SKPillars
version: '1.1.3'
main: net.adamcowell14.skpillars.SKPillars
api-version: '1.21'
author: "adamcowell14"
depend: ["WorldEdit", "PlaceholderAPI"]
commands:
  pillars:
    description: Режим столбы
  psetup:
    description: Режим столбы
  t:
    description: none